---
title: "Aula 09 - ações"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
runtime: shiny
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
r = getOption("repos")
r["CRAN"] = "http://cran.us.r-project.org"
options(repos = r)
install.packages("reshape2")
install.packages("corrplot")
library(purrr)
library(flexdashboard)
library(tidyquant)
library(tidyverse)
library(corrplot)
library(dplyr)
library(shiny)
library(plotly)
library(reshape2)
library(DT)

install.packages("recipes", dependencies = TRUE)
install.packages("rlang")
packageVersion("rlang")

```

Column {.sidebar}
----------------------------------------------------------------------
```{r}
selectInput(
  inputId = "acao",
  label = "Escolha a sua ação",
  choices = c("PETR4.SA", "TAEE11.SA", "GGBR3.SA", "SAPR4.SA", "BBDC4.SA")
)

selectInput(
  inputId = "periodo",
  label = "Escolha o período",
  choices = c("1M", "6M", "1A", "5A", "10A")
)
```

```{r}
filters = c("PETR4.SA", "TAEE11.SA", "GGBR3.SA", "SAPR4.SA", "BBDC4.SA")
prices = filters %>%
  tq_get(get = "stock.prices", from = "2012-01-01")

mcorr = prices %>% select(date,symbol,adjusted) %>% spread(symbol, adjusted)
mcorr[1]=NULL


tabela_periodo = data.frame(
  periodo = c("1M", "6M", "1A", "5A", "10A"),
  dias = c(30, 180, 365, 1825, 3650)
  )

```


Row {data-width=500}
-----------------------------------------------------------------------

### Ação

```{r}

renderPlotly({
   
  periodo = Sys.Date()-filter(tabela_periodo,
                              periodo == input$periodo)$dias
  
  prices %>%
    filter(date >= periodo, symbol == input$acao) %>%
    ggplot() + aes(x = date, y = adjusted) +
    geom_line() +
    labs(x = "", y = "Cotação") +
    ggtitle(label = input$acao)
})

```

### Todas as ações

```{r}
renderPlotly({
   periodo = Sys.Date()-filter(tabela_periodo,
                              periodo == input$periodo)$dias
   
   prices %>%
     filter(date>periodo) %>%
     ggplot()+ aes(x = date, y = adjusted, color = symbol) +
     geom_line() +
     labs(x = "", y = "Cotação")
})

```


Row{data-width=500}
-----------------------------------------------------------------------

### Cotações

```{r}
renderDataTable({
  periodo = Sys.Date()-filter(tabela_periodo,
                              periodo == input$periodo)$dias
  prices %>%
    filter(date>= periodo, symbol == input$acao)%>%
    arrange(desc(date)) %>%
    datatable() # tabela interativa
})
```

Row{data-width=500}
-----------------------------------------------------------------------

### Matriz Corr


```{r}
res <- cor(mcorr) # Corr matrix
corrplot(cor(mcorr), method ='number')

```


